image: fedora:latest

variables:
  DEPENDENCIES: chrpath vala gtk-doc
                gobject-introspection-devel libxml2-devel
                libsoup-devel glib2-devel gtk3-devel
                liboauth-devel totem-pl-parser-devel
                meson redhat-rpm-config gcc gcc-c++ glibc-devel

build_stable:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build --prefix=/usr
    - ninja -C _build
    - ninja -C _build install
    - ninja -C _build test

build_no_optional_libs:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build --prefix=/usr -Denable-grl-net=false -Denable-grl-pls=false
    - ninja -C _build
    - ninja -C _build install
    - ninja -C _build test
