image: fedora:latest

variables:
  DEPENDENCIES: chrpath
                vala
                gtk-doc
                gobject-introspection-devel
                libxml2-devel
                libsoup-devel
                glib2-devel
                gtk3-devel
                liboauth-devel
                totem-pl-parser-devel
                meson
                redhat-rpm-config
                gcc
                gcc-c++
                glibc-devel
                libabigail
  LAST_ABI_BREAK: 60d135ef64f16671bb0ab4079ecbc59bdc32cbc7

build_stable:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build --prefix=/usr
    - ninja -C _build
    - ninja -C _build install
    - ninja -C _build test

build_no_optional_libs:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES
  script:
    - meson . _build --prefix=/usr -Denable-grl-net=true -Denable-grl-pls=true
    - ninja -C _build
    - ninja -C _build install
    - ninja -C _build test
    - curl https://gitlab.freedesktop.org/hadess/check-abi/-/raw/main/contrib/check-abi-fedora.sh | bash
    - check-abi --parameters="-Denable-grl-net=true -Denable-grl-pls=true" ${LAST_ABI_BREAK} $(git rev-parse HEAD)
