.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH grilo-test-ui 1 "August 25, 2014"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
grilo-test-ui \- Grilo test UI
.SH SYNOPSIS
.B grilo-test-ui
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B grilo-test-ui
command.
.PP
\fBgrilo-test-ui\fP is a graphical interface for Grilo that allows the
user to perform queries and see their results.
.SH OPTIONS
.TP
.B \-h, \-\-help
Show summary of grilo-test-ui options.
.TP
.B \-\-help\-grl
Show summary of Grilo options.
.TP
.B \-\-help\-all
Show summary of all options.
.SH AUTHOR
This manual page was written by Alberto Garcia <berto@igalia.com>.
